### ISSUE TITLE
actor_infos keep increasing, never cleared up

### ISSUE THREAD

**Issue by atique81** [oulutan/ACAM_Demo#14]
Hello @oulutan ,

thanks very much for this wonderful repo. I have a few confusions regarding the paper and the implementation itself.

1. Although you mentioned in your paper how your work differs from and improves upon the [Actor Conditioned Relation Network (ACRN) paper](https://arxiv.org/pdf/1807.10982.pdf), I am still confused about the main improvements. I would highly appreciate if you could provide some intuitions about how your work improves upon ACRN.

2. It seems that [actor_infos](https://github.com/oulutan/ACAM_Demo/blob/master/object_detection/object_detector.py#L166) keep increasing and never cleared up, whereas, the tracks corresponding to the actors may have been deleted. Shouldn't you delete the actors from actor_infos whose corresponding tracks are deleted?

Thanks.

**Comment by oulutan** [comment]
Thank you!

1. We do have an updated version of the paper coming up, that will make things more clear. It should be out in a day or two on arxiv. ACRN takes the attention idea from [relational reasoning](https://arxiv.org/pdf/1706.01427.pdf) and applies it to actor and context. They use these relation features and apply convolutions on them. In contrast, we leverage these relations to generate attention maps, kind of similar to [attention](https://arxiv.org/pdf/1706.03762.pdf). These attention maps basically alter the original context features to be relevant to each actor. Additionally, since I3D Tail is being used, altering original features work better than generating completely new features (like relation feats).

2. That is a little bit tricky. I was doing something like that initially, but if you want to keep track of what happened in the video (like a summary) and dump that into some json file, you should keep all the actor information over time. These don't take too much memory and should be okay to keep them unless there are memory issues.

**Comment by atique81** [comment]
Thank you so much @oulutan ! I appreciate your feedback. I will be eagerly waiting for the updated version of the paper!

**Comment by oulutan** [comment]
Updated version of our paper is now available on arxiv!

**Comment by atique81** [comment]
Thanks! I will check it out.
