### ISSUE TITLE
What is the input to I3d?

### ISSUE THREAD

**Issue by atique81** [oulutan/ACAM_Demo#16]
Hello @oulutan ,

As per the demo code, it seems that the inputs to I3d network are the cropped cuboids, one for each detected actor. But, in your paper, you mentioned that the input to I3d network is the whole video. Am I missing something? I would appreciate your response.

Thanks

**Comment by oulutan** [comment]
Hi @atique81 ,

Yes, training/validation and demo uses different approaches. In training/validation we use the whole video as the input. This is because in AVA dataset the whole video context is usually relevant to the actors. 

For the demo, it was implemented for "surveillance" scenarios. In these settings, camera has significantly wider view and using the whole video as input is not feasible and most of the view is irrelevant to the current actor. For this reason, we crop tubelets around the actor that is twice the size of the detected bounding box (which becomes the context). We explained this in Section 4.5 in the paper.  

"Since the proposed model explicitly models the surrounding context, a larger area than the person’s tubelet is essential to model interactions. Due to the large view of surveillance videos, it is not feasible to process the entire scene. For this reason, square regions centered on the person’s location and twice the size of the person’s area are cropped and fed to the action detection framework.
The overall pipeline is shown in Fig. 6. First, we extract the actor tubes with a larger context area from the video using the detector and the tracker. Then, each detected tube is analyzed by the ACAM module for actions."

**Comment by atique81** [comment]
Thank you very much for the clarification. So, if I want to train on videos where the important contexts are just around the actor, I should actually follow the validation approach, right?

**Comment by oulutan** [comment]
Yes, that's what I would do if only the nearby context is relevant.

**Comment by atique81** [comment]
Thanks a lot! It really helps. Actually, I need to train your model on videos where all context is just around the actor. My only concern with feeding I3d with actor-centric cuboids is that it has to evaluate i3d head repeatedly, once for each actor which is a bottleneck.

**Comment by oulutan** [comment]
If there is some overlap between contexts of different actors, you can run "i3d head" once on the whole video and branch out context's for each actor. If there is no overlap, this wouldn't help and make it worse actually. 

If each actor/context is really independent, I would preprocess the videos first and crop and save different videos for each actor. This way you save time on cropping and memory as you can batch them separately.

**Comment by atique81** [comment]
Thanks a lot @oulutan for the insights and advice. I highly appreciate your quick and helpful feedback.
