### ISSUE TITLE
Is the person detector finetuned on AVA?

### ISSUE THREAD

**Issue by zhujiagang** [oulutan/ACAM_Demo#17]
Thanks for sharing your excellent work! I've not run the code but I am wondering whether the person detector you used is finetuned on AVA.  The detectors shown in your paper `F RCNN-NAS` and  `F RCNN-Resnet101` achieve high performance, with AP 97.10 and 95.97 on AVA, respectively. But I use a `FPN-ResNet101` trained on COCO (43 mAP on 80 categories) and it can only achieve nearly 70 AP on AVA. Finetuning models on AVA can improve the performance to ~90. Finetuning detector is a common practice in many papers solving AVA, like SlowFast, Long Term bank.

**Comment by oulutan** [comment]
Sorry for the late response, I have been travelling. 

For the main results that I am reporting, we did not fine-tune the detector on AVA. That was one of the arguments in the paper that if fine-tuned, detectors tend to lose generalizability. I currently do have a detector that is fine-tuned on AVA and it provided about a 1.5 mAP increase overall. These results are not in the paper. 

Are you thresholding the results from COCO-trained detector? AP calculation needs to have lower confidence detections so that it can rank the the detection properly. That might be the reason you are getting 70 AP on AVA.

**Comment by abc67ok** [comment]
Dear
we are hopping for your training and validation code release version , when will it be released?

**Comment by zhujiagang** [comment]
@oulutan Thank you for your response. I am thresholding the results and maybe funetuning can bring the confidence above the threshold.
